### ISSUE TITLE
Error while compiling for iOS

### ISSUE THREAD

**Issue by alwx** [evollu/react-native-firebase-analytics#10]
<img width="883" alt="screen shot 2016-06-26 at 19 50 53" src="https://cloud.githubusercontent.com/assets/911127/16363588/01d99cac-3be0-11e6-8bfb-991a8afe59b9.png">

Here is what I see when trying to compile my project for iOS. Everything was fine before adding FirebaseAnalitycs to this project.

**Comment by ghost** [comment]
UPDATE: I have the solution.

Add **$(inherited)** to **OTHER LINKING FLAGS** in your **Build Settings**

Yep same issue here. But I have it with react-native-fcm package.

**Comment by alwx** [comment]
@alexanderniebuhr it works, thanks.
(it should be added to readme file, of course)
