### ISSUE TITLE
Add or document way of disabling for debug builds

### ISSUE THREAD

**Issue by greenatwork** [evollu/react-native-firebase-analytics#19]
It would be great if there was a way to only enable this module in production builds. Whether the best course of action is to include something in the module, or provide an example of how to go about it in the documentation, I don't know.

**Comment by Dean177** [comment]
From the Readme:

```
const Analytics = require('react-native-firebase-analytics');

if (environment === 'staging') {
    Analytics.setEnabled(false);
}
```

**Comment by greena13** [comment]
Fiddlesticks. I thought I had seen it somewhere, but couldn't find it when I actually needed it.

I would argue that it could have its own heading to make it easier to find. Otherwise I am happy for this to be closed as an invalid issue. 

Thanks for your pointing it out @Dean117.

**Comment by Dean177** [comment]
Happy to help

**Comment by sibelius** [comment]
@greenatwork can u close this issue?
