### ISSUE TITLE
Disable analytics temporarily

### ISSUE THREAD

**Issue by xxsnakerxx** [evollu/react-native-firebase-analytics#2]
Hi! Thanks first of all!

Could you add this feature https://firebase.google.com/support/guides/disable-analytics ?

**Comment by xxsnakerxx** [comment]
Ha, ok, I forgot that it's opensource !!! :)

I'll create PR soon...

**Comment by xxsnakerxx** [comment]
Done https://github.com/evollu/react-native-firebase-analytics/pull/3

**Comment by evollu** [comment]
merged and published
