### ISSUE TITLE
Where do we need to put the code

### ISSUE THREAD

**Issue by bondanherumurti** [evollu/react-native-firebase-analytics#24]
So where do we need to put the code

```
var Analytics = require('react-native-firebase-analytics');

componentWillMount() {
  if (environment === 'staging') {
    Analytics.setEnabled(false);
  }


  Analytics.setUserId('11111');
  Analytics.setUserProperty('propertyName', 'propertyValue');

  Analytics.logEvent('view_item', {
    'item_id': 'login'
  });

}
```

on every screen.js / index.ios.js ? and what is UserID? is that custom property or property defined from Google?

**Comment by alexHlebnikov** [comment]
You need to add it onlue in your App.js (or something) - in your root component.

**Comment by alexHlebnikov** [comment]
UersID is the same thing as Device ID, you can get it with this package https://github.com/rebeccahughes/react-native-device-info

**Comment by evollu** [comment]
looks like solved
