### ISSUE TITLE
Does this package automatically collect events?

### ISSUE THREAD

**Issue by luisfpinto** [evollu/react-native-firebase-analytics#26]
Hello! I was wondering if your package support this: https://support.google.com/firebase/answer/6317485 without doing anything with it or otherwise I have to log all events manually. So for example if I want to log first_open or app_update, does this package do it automatically? Or have I to log it manually an put this on my app?

Thanks!

**Comment by evollu** [comment]
it logs

**Comment by jonashaag** [comment]
What does this mean? Does it log stuff automatically, and if so which things?

**Comment by evollu** [comment]
app level events like first_open or app_update are automatically logged by firebase SDK. please check their documentation about what they log default.
for other events like `view` or transactions, you need to log manually.
