### ISSUE TITLE
How can I log custom events?

### ISSUE THREAD

**Issue by luisfpinto** [evollu/react-native-firebase-analytics#29]
I'm doing like

```
Analytics.logEvent('view_item', {
        'item_id': 'Login'
      })
```

However If I put a custon event like 

```
Analytics.logEvent('ADD_NAME', {
        'name': 'John'
      })
```

If I see the audiences and select the custom audience I can't see the property name on the list. Any tip with this?

**Comment by mvayngrib** [comment]
@luisfpinto how did you end up solving this problem?

**Comment by mvayngrib** [comment]
nm, it seems they're logged just fine, just had a config issue.
