### ISSUE TITLE
Problems with IOS installation

### ISSUE THREAD

**Issue by avkvak** [evollu/react-native-firebase-analytics#31]
[thats](https://cl.ly/3T303N1H3m0U) what I see when I try to install react-native-firebase-analytics in my project. What I do wrong? Sorry for the stupid question, and thanks in advance

**Comment by ghost** [comment]
I Have the same issue

**Comment by darkrishabh** [comment]
You have to set this setting @avkvak @NicolasDinunno 

and in AppDelegate.m import the header "@import Firebase;"
<img width="1668" alt="screen shot 2016-10-28 at 7 05 09 pm" src="https://cloud.githubusercontent.com/assets/812474/19826513/7d6acc16-9d41-11e6-8eb0-f964501eeff2.png">

**Comment by avkvak** [comment]
Thank you. It solved my problem

**Comment by eneskaya** [comment]
Why isn't that already set in the project? Because every time I reinstall the node_modules I have to think of resetting it
