### ISSUE TITLE
IOS setup problem

### ISSUE THREAD

**Issue by SerzN1** [evollu/react-native-firebase-analytics#35]
Hello guys. I have a problem with build after installation pod file.

warning
```
ld: warning: directory not found for option '-L/Users/serzn1/Library/Developer/Xcode/DerivedData/Counter-edtbdpnhstjryegnyhppxrhswrgb/Build/Products/Debug-iphonesimulator/GoogleToolboxForMac'
```

error
```
ld: library not found for -lGoogleToolboxForMac
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

How to resolve this problem?

**Comment by evollu** [comment]
if you are doing manual import, remove all old files you've imported and download the latest version of SDK.

**Comment by SerzN1** [comment]
I have just installed manually GoogleToolboxForMac Pod and ...

Two more problems. 
1st - Push notifications reject application in itunes connect
2nd - Binary rejected because of Non-public API usage

... troubles, troubles 
It's a pity system when I didn't have chance just use `pod install`

**Comment by evollu** [comment]
can you elaborate what is the reason for rejection?
Those SDKs are all public right?

**Comment by SerzN1** [comment]
@evollu 

> Non-public API usage:
> 
> The app references non-public selectors in Counter: _terminateWithStatus:
> If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.
> 
> If you think this message was sent in error and that you have only used Apple-published APIs in accordance with the guidelines, send the app's nine-digit Apple ID, along with detailed information about why you believe the above APIs were incorrectly flagged, to appreview@apple.com. For further information, visit the Technical Support Information page.
> 

I had to rename `_terminateWithStatus` method to `_terminateWithStatusModifed` to temporarily solve our problem. 
??? 
It was one of the stupidest thing I have ever done. 


And also earlier:

> Though you are not required to fix the following issues, we wanted to make you aware of them:
> 
> Missing Push Notification Entitlement - Your app includes an API for Apple's Push Notification service, but the aps-environment entitlement is missing from the app's signature. To resolve this, make sure your App ID is enabled for push notification in the Provisioning Portal. Then, sign your app with a distribution provisioning profile that includes the aps-environment entitlement. This will create the correct signature, and you can resubmit your app. See "Provisioning and Development" in the Local and Push Notification Programming Guide for more information. If your app does not use the Apple Push Notification service, no action is required. You may remove the API from future submissions to stop this warning. If you use a third-party framework, you may need to contact the developer for information on removing the API.

Why should I do some magic with push notifications? Does it work through notification service?

**Comment by evollu** [comment]
I think what it means it that you didn't declare the usage for push notification in `Capabilities` tab

**Comment by SerzN1** [comment]
As a fact it doesn't work from the box.
About Cap tab - yes, but it doesn't described in your readme (It's poor) and we don't use any Push notifications directly. May be there are some usage in GoogleToolBox or Firebase modules.
