### ISSUE TITLE
Enable Verbose Logging

### ISSUE THREAD

**Issue by adamgeoffrion** [evollu/react-native-firebase-analytics#43]
Is there anyway to enable verbose logging to view in the debug console? https://firebase.google.com/docs/analytics/ios/events#view_events_in_the_xcode_debug_console

**Comment by adamgeoffrion** [comment]
I was able to accomplish this through the Xcode build and adding the argument like described in the link.

**Comment by annelorraineuy** [comment]
On Android you can do:

```
adb shell setprop log.tag.FA VERBOSE
adb shell setprop log.tag.FA-SVC VERBOSE
adb logcat -v time -s FA FA-SVC
```
