### ISSUE TITLE
import FCMModule.h did not work

### ISSUE THREAD

**Issue by eljago** [evollu/react-native-firebase-analytics#5]
Hello. in order to make **[FIRApp configure];** work in the ios setup, I had to do **@import Firebase;** (Objective-C) instead of **#import 'FCMModule.h'** in my AppDelegate. 
I got this from https://firebase.google.com/docs/ios/setup
Did I do something wrong ? or this way is also ok?

ty

**Comment by evollu** [comment]
sorry the document is outdated. you should `import RNFIRMessaging.h`.

**Comment by evollu** [comment]
let me know if this solves your issue

**Comment by evollu** [comment]
The README is wrong. it should be either `@import Firebase` or "import RNFIRAnalytics.h"

**Comment by evollu** [comment]
read me updated

**Comment by evollu** [comment]
thank you for the issue

**Comment by bitcoinvsalts** [comment]
I dont see this change on the readme
