### ISSUE TITLE
RNFIRAnalytics.h has error "file not found" with #import "Firebase.h"

### ISSUE THREAD

**Issue by giangdoan** [evollu/react-native-firebase-analytics#7]
I installed the module and use `#import "Firebase.h"` in `AppDelegate.m` successfully (file found). However in `RNFIRAnalytics.xcodeproj`, `RNFIRAnalytics.h` has an error **file not found** with `#import "Firebase.h"` and build failed. Am I missing something? Thanks.

**Comment by evollu** [comment]
sounds like `RNFIRAnalytics.xcodeproj` can't find the Pod files. It searches file in `/ios/Pods`. Is it where you install your pods?

**Comment by giangdoan** [comment]
Lol I didn't use pods so I installed the frameworks myself by dragging them to the project and add them to `Link Binary With Libraries`. Is there a way to workaround with it or do I have to use pods? Thanks.

**Comment by evollu** [comment]
sure, you need to add header search path for RNFIRAnalytics target.
If your approach is generic enough, a pull request is welcomed

**Comment by evollu** [comment]
however, Pods are recommended because it helps you to keep up to date

**Comment by giangdoan** [comment]
👍 Thanks. I updated `Frameworks Search Path` and `Libraries Search Path` and it works. I am going to switch to Pods.

**Comment by danvass** [comment]
@giangdoan @evollu I'm trying to do this by manually adding the firebase SDK to ios and appdelegate.m is able to find Firebase.h but the library is not. What should I set the search paths too?

**Comment by evollu** [comment]
it searches header file in /ios folder

**Comment by danvass** [comment]
@evollu that's where I have the firebase framework but still gives the error

**Comment by evollu** [comment]
can you share an example repo?
