### ISSUE TITLE
missing screenClass on screenView

### ISSUE THREAD

**Issue by sibelius** [evollu/react-native-firebase-analytics#71]
based on this https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#setCurrentScreen(android.app.Activity, java.lang.String, java.lang.String)

and this one https://github.com/invertase/react-native-firebase/blob/master/lib/modules/analytics/index.js#L77

**Comment by evollu** [comment]
@sibelius do you think it makes more sense to just deprecate this lib and use react-native-firebase?

**Comment by sibelius** [comment]
maybe this is a good idea

what about https://github.com/evollu/react-native-fcm?

**Comment by evollu** [comment]
@sibelius that will still be maintained because it has more features than firebase

**Comment by sibelius** [comment]
gonna move to this one instead https://github.com/invertase/react-native-firebase

tks

**Comment by sibelius** [comment]
what about merging react-native-fcm with react-native-firebase

are they willing to add all the features from react-native-fcm there?
