### ISSUE TITLE
Tracking user actions

### ISSUE THREAD

**Issue by alexHlebnikov** [evollu/react-native-firebase-analytics#8]
Hi! 
Thanks for the component.

Is there a way to track certain user action with this component (for example, certain user clicks, searches, etc)? 
If I correctly understand, I need to get Device ID and track user according to it. So I need to write a bridge ObjectiveC - RN for this? Or there any other ways to do it?

**Comment by alexHlebnikov** [comment]
@evollu can you help me with my question?

**Comment by evollu** [comment]
you can use 

```
Analytics.setUserId('11111');
Analytics.setUserProperty('propertyName', 'propertyValue');
```
