### ISSUE TITLE
Install this package and Firebase Crash?

### ISSUE THREAD

**Issue by rturk** [evollu/react-native-firebase-analytics#9]
Hi is possible to install this package and Firebase Crash Report?

**Comment by alexHlebnikov** [comment]
@rturk 
You don't need this package to install Crash Reporting - just check install guides here: https://firebase.google.com/docs/crash/

**Comment by rturk** [comment]
Hi @alexHlebnikov I can't make the two packages work together.

**Comment by alexHlebnikov** [comment]
@rturk 
Why there are two packages? Only this one.
For iOS, you just need to add _Crash_ in your .pod file, it must be something like this:

```
pod 'Firebase/Core'
pod 'Firebase/Crash'
```

And then follow instructions here (see paragraph **Upload symbol files**): https://firebase.google.com/docs/crash/ios

**Comment by evollu** [comment]
looks like the issue is solved

**Comment by rturk** [comment]
@evollu @alexHlebnikov Tks. I'll try again and comment my progress in this thread. I'm not using cocoapods I'm installing the SDK manually.

**Comment by evollu** [comment]
they should live with each other nicely

**Comment by rturk** [comment]
Hi all I've managed to make both Analytics and Crash work on IOS manually installing the SDK.

**Comment by annelorraineuy** [comment]
^ Same here. I used this for Crash https://github.com/ianlin/react-native-firebase-crash-report
